### ISSUE TITLE
Polygon begins with an inner ring

### ISSUE THREAD

**Issue by hfu** [hfu/produce-220#1]
```
thanks:produce-220 hfu$ node index.js
For layer 0, using name "pullrfc8142"
../welt/pull.rfc8142:0: null geometry (additional not reported)
In JSON object {"type":"Feature",***                                       
../welt/pull.rfc8142:0: ignoring dimensions beyond two
In JSON object [***]
In JSON object {"type":"Feature",***
12978862 features, 3395336223 bytes of geometry, 6972 bytes of separate metadata, 19241635 bytes of string pool                                              
2019-03-22T08:24:01.717Z: 0/0/0
Polygon begins with an inner ring
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:792:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:794:10)
```

**Comment by hfu** [comment]
このエラーメッセージは、tippecanoe が作るものである。
https://github.com/mapbox/tippecanoe/blob/master/write_json.cpp

**Comment by hfu** [comment]
`--use-source-polygon-winding` をつけて、だめもとでやってみるか。

**Comment by hfu** [comment]
`--use-source-polygon-winding` を使ってみたところ、かえってエラーが増加した。

**Comment by hfu** [comment]
`--check-polygons` をつけて、どうにか進めてみる。
